# Env definition file for creating environment via conda

name: cmatools-env
channels:
 - conda-forge
dependencies:
 # core
 - python=3.9
 - iris>=3.0
 - numpy>=1.19
 - pandas
 - xarray
 - jupyter
 # codestyle
 - black
 # testing
 - nccmp
 - coverage
 - pytest
 - pytest-cov
 # documentation
 - sphinx
 - sphinx_rtd_theme
 - sphinx-argparse
 - sphinx-gallery
 - sphinxcontrib-mermai
 # visualisation
 - holoviews
 - geoviews
# other
 - pip
 - cdsapi
 - libnetcdf
