# Env definition file for creating environment via conda

name: cmatools-dev-env
channels:
 - conda-forge
dependencies:
 # core
 - python=3.9
 - iris>=3.0
 - numpy>=1.19
 - pandas
 # codestyle
 - black
 # testing
 - coverage
 - pytest
 - pytest-cov
 - nccmp
 - cfchecker
 - compliance-checker
 # documentation
 - sphinx
 - sphinx_rtd_theme
 - sphinx-argparse
 - sphinx-gallery
 - sphinxcontrib-mermaid
 # visualisation
 - holoviews
 - geoviews
 # other
 - cdsapi
 - libnetcdf
 - pip

# Removed from dev environment to speed up builds, installs, uninstalls
# - xarray
# - jupyter
