# Env definition file for creating environment via conda

name: cmatools-min
channels:
  # make sure conda-main is not listed here (MO-L)
  - conda-forge
  - nodefaults
dependencies:
 - python=3.9
 - black
 - pre-commit
 - isort
 - flake8
 - pytest
 - pip
